-- MySQL Script generated by MySQL Workbench
-- Fri Jul  7 14:05:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dev_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dev_db` ;

-- -----------------------------------------------------
-- Schema dev_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dev_db` DEFAULT CHARACTER SET utf8 ;
USE `dev_db` ;

-- -----------------------------------------------------
-- Table `dev_db`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`companies` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`companies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dev_db`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`customers` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`customers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dev_db`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`projects` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NOT NULL,
  `Customers_id` INT(11) NOT NULL,
  `Companies_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Projects_Customers1_idx` (`Customers_id` ASC),
  INDEX `fk_Projects_Companies1_idx` (`Companies_id` ASC),
  CONSTRAINT `fk_Projects_Companies1`
    FOREIGN KEY (`Companies_id`)
    REFERENCES `dev_db`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_Customers1`
    FOREIGN KEY (`Customers_id`)
    REFERENCES `dev_db`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dev_db`.`developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`developers` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`developers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `Projects_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Developers_Projects1_idx` (`Projects_id` ASC),
  CONSTRAINT `fk_Developers_Projects1`
    FOREIGN KEY (`Projects_id`)
    REFERENCES `dev_db`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dev_db`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`skills` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`skills` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `skills` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dev_db`.`developers_has_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_db`.`developers_has_skills` ;

CREATE TABLE IF NOT EXISTS `dev_db`.`developers_has_skills` (
  `Developers_id` INT(11) NOT NULL,
  `Skills_id` INT(11) NOT NULL,
  PRIMARY KEY (`Developers_id`, `Skills_id`),
  INDEX `fk_Developers_has_Skills_Skills1_idx` (`Skills_id` ASC),
  INDEX `fk_Developers_has_Skills_Developers1_idx` (`Developers_id` ASC),
  CONSTRAINT `fk_Developers_has_Skills_Developers1`
    FOREIGN KEY (`Developers_id`)
    REFERENCES `dev_db`.`developers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Developers_has_Skills_Skills1`
    FOREIGN KEY (`Skills_id`)
    REFERENCES `dev_db`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
